## import math


In [14]:
import numpy as np
import matplotlib.pyplot as plt


In [21]:
em7b5 = np.array([329,493,783,587])
Eb7 = np.array([311,392,466,554])
dm6 = np.array([293,349,440,493])

fs = 48000
sec = 3

oneNote = np.linspace(0,sec,sec*fs,False)

chords = [ [np.sin(note*oneNote*2*np.pi) for note in chord] for chord in [em7b5,Eb7,dm6] ]
chords2 = np.array(list(map(lambda chord: chord[0]+chord[1]+chord[2]+chord[3]/4,chords))).flatten()


In [16]:
np.array(np.sin(440*oneNote*2*np.pi))
fl = list(map(float,np.array(np.sin(440*oneNote*2*np.pi))))

In [17]:

f = open("output2.bin","w")
t = [x.astype('>f4').tobytes() for x in np.array(fl)]
for e in t:
    f.writelines(str(e))

In [13]:
plt.plot(chords[0], "g", label="Sin")

KeyboardInterrupt: 

Error in callback <function flush_figures at 0x7f0f006721f0> (for post_execute):


KeyboardInterrupt: 

In [18]:
chords

[[array([ 0.        ,  0.04305269,  0.08602554, ..., -0.12883887,
         -0.08602554, -0.04305269]),
  array([ 0.        ,  0.06448877,  0.12870906, ..., -0.19239351,
         -0.12870906, -0.06448877]),
  array([ 0.        ,  0.1023151 ,  0.20355631, ..., -0.30266101,
         -0.20355631, -0.1023151 ]),
  array([ 0.        ,  0.07676253,  0.15307207, ..., -0.22847831,
         -0.15307207, -0.07676253])],
 [array([ 0.        ,  0.04069856,  0.08132968, ..., -0.12182604,
         -0.08132968, -0.04069856]),
  array([ 0.        ,  0.05129017,  0.10244531, ..., -0.15333078,
         -0.10244531, -0.05129017]),
  array([ 0.        ,  0.06096144,  0.12169611, ..., -0.1819781 ,
         -0.12169611, -0.06096144]),
  array([ 0.        ,  0.07245489,  0.1445289 , ..., -0.21584319,
         -0.1445289 , -0.07245489])],
 [array([ 0.        ,  0.03834421,  0.07663202, ..., -0.11480712,
         -0.07663202, -0.03834421]),
  array([ 0.        ,  0.0456681 ,  0.09124091, ..., -0.13662334,
     

In [30]:
audio = note * (2**15-1) / np.max(np.abs(note))
audio = audio.astype(np.int16)

In [28]:
play = sa.pl

array([ 0.        ,  0.06264832,  0.12505052, ..., -0.18696144,
       -0.12505052, -0.06264832])

In [8]:
f = open("demo.bin","a")
f.write([math.sin(x*0.01) for x in range(0,48000)])
f.close

TypeError: write() argument must be str, not list